language: node_js
node_js:
  - '8'

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn global add now

script: echo "Building and deploying karl.run"

jobs:
  include:
    - stage: build
      script:
        - yarn build
    - stage: deploy
      script:
        - now --token $NOW_TOKEN && now --token $NOW_TOKEN alias

stages:
  - build
  - name: deploy
    if: branch = master AND type IN (push)
